### PR TITLE
Upgrade compile and target sdk version to Android API 31 (version 2.9.1)

### PR DESCRIPTION
**Pull request by fluiddot**
Incorporate changes from https://github.com/wordpress-mobile/react-native-reanimated/pull/19 into version [2.9.1-wp-1](https://github.com/wordpress-mobile/react-native-reanimated/releases/tag/2.9.1-wp-1).

### CODE REVIEW

**Comment by fluiddot** [comment]
Not sure why but when running `./createNPMPackage.sh` command, it fails with the following error:
```
+ mv android android-temp
+ mv android-npm android
+ cp -R android/build build_output
cp: android/build: No such file or directory
```

However, I'm able to reproduce this same issue in `wp-fork` branch so not sure if generating the NPM package requires something else in version 2.9.1. @geriux any idea? Thanks!

**Comment by geriux** [comment]
Hello @fluiddot 👋 

After cleaning some local folders the script started to failed for me as well. I compared the code with the upstream code in `2.9.1` and there were some lines that should've been removed. It looks like there was an issue with the merge.

I created [this PR](https://github.com/wordpress-mobile/react-native-reanimated/pull/22) that updates the script.

**Comment by fluiddot** [comment]
> Hello @fluiddot 👋
> 
> After cleaning some local folders the script started to failed for me as well. I compared the code with the upstream code in `2.9.1` and there were some lines that should've been removed. It looks like there was an issue with the merge.
> 
> I created [this PR](https://github.com/wordpress-mobile/react-native-reanimated/pull/22) that updates the script.

Great, thanks for fixing the issue 🙇 . I've just approved and merged [the PR](https://github.com/wordpress-mobile/react-native-reanimated/pull/22) that updates the script.

**Review by geriux — APPROVED** [review]
LGTM! Thanks for updating this 🙇

**Pull request merged**
